= POCA
:toc:
:toc-placement: preamble
:toclevels: 2
:showtitle:
:!webfonts:

// Need some preamble to get TOC:
{empty}

== Introduction

POCA is JavaScript/ECMAScript-like, but it's not the same. It has some
differences and even a few features that ECMAScript doesn't have.

This document shows the features of POCA. POCA is a very powerful scripting
language, that uses some of the concepts coming from ECMAScript, Lua, Squirrel,
Nasal, Python, and Perl. POCA supports object-oriented programming (OOP) in two
flavours (prototype-based and class-based), as well as functional programming
and procedural programming styles.

In POCA everything is an expression; there are no statements, so for example
something like

[source,javascript]
----
var a = scope {
  var b = 1;
  for (reg c = 0; c < 16; c++) {
    b += c + c
  };
  b;
};
----

and

[source,javascript]
----
var a = if (b < 1) {
          1
        } else if (b < 4){
          2
        } else {
          3
        };
----

is valid POCA code.

People familiar with other programming languages, especially scripting
languages such as JavaScript/ECMAScript in particular, are usually able to
learn POCA fairly quickly.

== Architecture

POCA uses a frame stack, infinite register, bytecode instruction set
architecture (ISA).

Unlike almost all other script interpreters, POCA is thread-safe and scalable
when called from multiple CPU threads. No special handling is required and the
threads can be scheduled concurrently. There is no global lock (GIL) on the g
interpreter or the x86 just in time (JIT) compiler execution engine. The only
limit to scalability is the single-threaded incremental and generational
garbage collector, which must block all bytecode interpreter threads and CPU
native code threads compiled by the JIT compiler before executing.

POCA's API design concept is more or less similar to Lua's. This means that
concepts like hash tables (hashes), meta tables (hash table events), vectors
(arrays), etc. exist here too.

== Overview

=== Imperative and structured

POCA supports structured programming in the style of C. POCA supports function
and block scoping with the keywords var, let and const. POCA requires explicit
semicolons, as automatic semicolon injection can introduce hard-to-detect bugs.
The only exception is that you can omit the last semicolon in a `function`,
`scope`, or `code` block.

As with C-like languages, control flow can be achieved using `while`, `for`,
`do` / `while`, `if` / `else`, and `switch` / `case` statements. Functions are
weakly typed and can accept and return any type. Unspecified arguments default
to undefined. In addition to `for`, POCA also supports `foreach`, which can
iterate over ranges (arrays).

=== Weakly typed

POCA, like ECMAScript/JavaScript, is weakly typed. This means that in most, but
not all cases, certain types are implicitly assigned based on the operation
being performed, avoiding some typical JavaScript/ECMAScript quirks.

=== Dynamic

POCA is dynamically typed. Thus, a type is associated with a concrete value and
not with an expression. POCA supports several ways to test the type of objects,
including duck typing.

=== Everything is an expression

In POCA, everything is an expression, even statements, declarations and
definitions. So the following code snippet is valid:

[source,javascript]
----
let a = scope{let b = 0; for(let c = 0; c < 6; c++){ b++ }; b; };
let bla = if(a != 0){ 1 }else{ a ? 2 : 3 };
----

POCA essentially maps the mathematical concept and expression of "something"
into a complete scripting language.

=== Scoping

POCA supports lexical scoping. This means that the scope of a variable is
determined by its position in the source code. 

Variables declared with `var` are local-scoped, which means they are 
accessible only within the scope in which they are declared and any nested 
scopes. This is similar to how variables are scoped in JavaScript and ECMAScript, 
where variables declared with `var` are function-scoped. These variables are 
stored in a local hash table and are accessible from the current frame and all 
nested frames.

However, variables declared with `let` and `const` are block-scoped as well, 
but unlike `var`, they are not accessible beyond the *execution context frame* 
boundaries, such as a function or the global scope. Because of this, POCA 
assigns so-called "registers" to variables declared with `let` and `const`. 
These variables are not stored in the local hash table but directly in the 
VM's registers. VM registers are frame-specific, which means they cannot be 
accessed from outside the current frame.

This is different from JavaScript and ECMAScript, where variables declared
with `let` and `const` are block-scoped but can still be accessed from
the outer scope.

Here are some scoping examples in POCA to show what the above means:

[source,javascript]
----

let a = 1;

var b = 2;

function Func1(){
  // a is not accessible here, but b is accessible
  let c = 3;
  var d = 4;
  function Func2(){
    // b and d are accessible here, but a and c are not
    // ...
  }
}

----

POCA also supports closures, which means that functions can capture and
remember the environment in which they were created, even if that
environment is no longer in scope.

This allows for powerful programming techniques, such as creating
functions that can maintain state or encapsulate private variables.

POCA also supports the `scope` and `code` keywords to create explicit
scopes. The `scope` keyword creates a new scope, while the `code` keyword
creates a new code block without introducing a new scope. This allows for
more control over variable visibility and lifetime.

== A quick tour

=== How to declare variables

[source,javascript]
----
var x;
let y;
----

=== How to use variables

[source,javascript]
----
x = 5;
y = 6;
let z = x + y;
----

=== Values

The POCA syntax defines two types of values:

* Fixed values
* Variable values

Fixed values are called Literals.

Variable values are called Variables.

=== Literals

The two most important syntax rules for fixed values are:

Numbers are written with or without decimals:

[source,javascript]
----
10.50

1001
----

Strings are text, written within double or single quotes:

[source,javascript]
----
"John Doe"

'John Doe'
----

=== Variables

In a programming language, variables are used to store data values.

POCA uses the keywords var, let and const to declare variables.

An equal sign is used to assign values to variables.

In this example, x is defined as a variable. Then, x is assigned (given) the value 6:

[source,javascript]
----
let x;
x = 6;

// or

let x = 6;
----

=== Operators

POCA uses arithmetic operators ( + - * / ) to compute values:

[source,javascript]
----
(5 + 6) * 10
----

POCA uses an assignment operator ( = ) to assign values to variables:

[source,javascript]
----
let x, y;
x = 5;
y = 6;
----

=== Expressions

An expression is a combination of values, variables, and operators, which computes to a value.

The computation is called an evaluation.

For example, 5 * 10 evaluates to 50:

[source,javascript]
----
5 * 10
----

Expressions can also contain variable values:

[source,javascript]
----
x * 10
----

The values can be of various types, such as numbers and strings.

For example, `"John" ~ " " ~ "Doe"`, evaluates to `"John Doe"`, since `~` is using for string concatenation:

[source,javascript]
----
"John" ~ " " ~ "Doe"
----

=== Keywords

POCA keywords are used to identify actions to be performed.

The `let` keyword is used to create variables:

[source,javascript]
----
let x = 5 + 6;
let y = x * 10;
----

The `var` keyword is also used to create variables:

[source,javascript]
----
var x = 5 + 6;
var y = x * 10;
----

However, the `const` keyword is also used to create constants:

[source,javascript]
----
const x = 5 + 6;
const y = x * 10;
----

=== Comments

Not all POCA statements are "executed".

Code after double slashes `//` or between

[source,javascript]
```
/*
```

and

[source,javascript]
```
*/
```

is treated as a comment.

Comments are ignored, and will not be executed:

[source,javascript]
----
let x = 5;   // I will be executed

// x = 6;   I will NOT be executed
----

=== Identifiers / Names

Identifiers are POCA names.

Identifiers are used to name variables and keywords, and functions.

The rules for legal names are the same in most programming languages.

A POCA name must begin with:

* A letter (A-Z or a-z)
* A dollar sign ($)
* Or an underscore (_)

Subsequent characters may be letters, digits, underscores, or dollar signs.

Numbers are not allowed as the first character in names.

This way POCA can easily distinguish identifiers from numbers.

=== POCA is Case Sensitive

All POCA identifiers are case sensitive.

The variables lastName and lastname, are two different variables:

[source,javascript]
----
let lastName = "Doe";
let lastname = "Peterson";
----

POCA does not interpret LET or Let as the keyword let.

=== POCA Character Set

POCA uses the Unicode character set together with the UTF8 internal encoding.

Unicode covers (almost) all the characters, punctuations, and symbols in the world.

== Learning by examples

=== Definitions

[source,javascript]
----
a = 3.14159;                    // a is then inside in the current environment hash table
var b = 0x10000;                // b is then inside in the current environment hash table
register c = 0b10101;           // c is then assigned to a VM-register
reg d = 0b10101;                // reg is a syndrom for register
let e = 0o77777;                // let is also a syndrom for register
const f = "This is a constant";

var (g, h) = (0, 1);
(g, h) = (h, g);

function bla(){
  return [1, 2, 3]:
}

let (x, y, z) = bla();
----

=== Scope and code blocks

POCA distinguishes between object/hash literals and code blocks based on their content. Object literals are defined by key-value pairs separated by colons (`:`) and commas (`,`). Code blocks consist of expressions or statements without this pattern. The `scope` and 'code' keywords can be used to explicitly define a code block when ambiguity might arise, as everything in POCA is treated as an expression.

[source,javascript]
----
// Example object literal with multiple keys
{ name: "Alice", age: 30 }

// Example object literal with a single key-value pair
{ Name: "Alice" }

// Example shorthand object literal
{ name, age } // Assuming 'name' and 'age' are defined variables, it expands to { name: name, age: age }

// Example object literal with a single shorthand key
{ name } // Assuming 'name' is defined, it expands to { name: name }

// Example code block
{ name; } // This is treated as a code block, because of the semicolon, for distinguishing it from an shorthand object literal

// Example code block
{ print("Hello"); }

// Explicit code block using 'scope' where a new scope is created
scope {
  let x = 10;
  print(x);
}

// Example code block using 'code' where no new scope is created
code {
  let y = 20;
  print(y);
}

// Example of nested code blocks with explicit 'scope' and 'code' keywords
scope {
  let a = 1 + 2;
  code {
    let b = a + 2;
    print(b);
  }
}

----

Without the `scope` and `code` keyword, POCA relies on the presence of key-value pairs (identifiers followed by a colon and value) to identify object literals. If no such pattern is found within the curly braces, it's treated as a code block. However, empty curly braces `{}` are always treated as an empty object literal, since inside code blocks, these are anyway effectively no-ops and will be garbage collected later.

This distinction allows for flexibility in defining both objects and code blocks, making POCA's syntax versatile.

=== Arrays/Vectors

[source,javascript]
----
let va = [1, 2, 3];
let vb = [4, 5, 6];
let vc = (va ~ vb) ~ [7, 8, 9];  // ~ is the concatenation operator for arrays, strings, etc.
let vd = vc[0 .. 4];             // range slice copy

va.push(21);
va.push(42);
va.push(1337);

for(let i = 0; i < va.size(); i++){
  puts(va[i]);
}

foreach(let arrayElement in vd){
  puts(arrayElement);
}

while(!va.empty()){
  va.pop();
}

function Bla(){
  return [1, 2, 3];
}

let (a, b, c) = Bla();

puts(a, " ", b, " ", c);
----

=== Hashs/Prototyping/Objects

[source,javascript]
----
let aHash = {
              bla: "bla!",
              bluh: "bluh?"
            };

foreach(let hashElement; aHash){
  puts(hashElement);
}

function oa(){
  return {};
}

var x = {a: 12, y:() => puts(@a)};
let y = {prototype: x, b: 34};
let z = {prototype: y, c: 56};
const p = {b: 42, "c": 41};

puts(x.a);
puts(y.a);
puts(z.a);
puts();

y.a=13;

puts(x.a);
puts(y.a);
puts(z.a);
puts();

z.a=14;

puts(x.a);
puts(y.a);
puts(z.a);
puts();

x.y();
y.y();
z.y();

readLine();
----

=== Functions/Lambdas

[source,javascript]
----
function Test1(a, b){
  return (a + b) * 2;
}

function Test2(reg a, reg b){
  return (a + b) * 2;
}

function Test3(let a, let b){
  return (a + b) * 2;
}

fastfunction Test4(reg a, reg b){
  return (a + b) * 2;
}

fastfunction Test5(reg a, reg b){
  return (a + b) * 2;
}

let u(x=(4)) -> x * x;

puts(u());

y(x) -> x * x;

puts(y(4));

let z=(x)=>x + x;

puts(z(4));

let w=function(x)(x * x) - x;

puts(w(4));

let a = function(x){
 return (x * x) - x;
}

puts(a(4));

let function b(x){
  return (x * x) - x;
}

puts(b(4));

f(x) -> x + 3;
function g(m, x) m(x) * m(x);
puts(g(f, 7));

function searchPrimes(reg from, reg to){
  let (dummy, primes, n, i, j, isPrime) = (0, 0, 0, 0, 0, 0);
  from = +from;
  to = +to;
  for(n = from; n<= to; ++n){
    i = ((n % 2) === 0) ? 2 : 3;
    j = n ** 0.5;
    isPrime = 1;
    while(i <= j){
      if((n % i) === 0){
        isPrime = 0;
        break;
      }
      i += 2;
    }
    primes += isPrime;
  }
  return primes;
}
----

=== Threads

[source,javascript]
----
var terminated = 0;

function thread1function(){
  while(!terminated){
    puts("Thread 1");
  }
}

var thread1 = new Thread(thread1function);

var thread2 = new Thread(function(){
  while(!terminated){
    puts("Thread 2");
  }
});

thread1.start();
readLine();

thread2.start();
readLine();

terminated = 1;

thread1.wait();
thread2.wait();
----

=== Coroutines

[source,javascript]
----
function testcoroutinefunction(i){
  while(1){
    Coroutine.yield(i += Coroutine.get());
  }
}

var testcoroutine = new Coroutine(testcoroutinefunction, 1000);
print("Go!\r\n");
print(testcoroutine.resume(100), "\r\n");
print(testcoroutine.resume(10), "\r\n");
print(testcoroutine.resume(1)," \r\n");
readLine();
----

=== Classes

[source,javascript]
----
var a = 12, b = 4;

class Test extends BaseClass {

  var a = 0;

  constructor(reg v){
    this.a = v + 1;
  }

  function init(reg v){
    this.a = v + 1;
  }

  function b(){
     puts(this.a);
  }

}

class TestB extends Test {

  var x = 0;

  constructor(reg v){
    super(v * 2);
    this.x = v + 1;
  }

  function b(){
     super();    // calls previous Test.B
     super.b();  // also calls previous Test.B
     super.c();  // also previous Test.c
     this.a--;
     super.b();  // also calls previous Test.B
     puts(this.x);
  }

}

function Test.c(){
  puts(if(this.a === 247) "yeah" else "ups");
}

function Test::d(){
  puts((this.a === 247) ? "allright" : "fail!");
}

Test.e = function(){
  puts((this.a === 247) ? ":-)" : ":-(");
}

let bla = new Test(246);

puts(bla.a, " ", a, " ", b);

bla.b();
bla.c();
bla.d();
bla.e();

puts();

puts("Keys of object bla instance of class ",bla.className,":\n", scope{
  let s = "";
  forkey(key;bla){
    s ~= key ~ " of type " ~ typeof(bla[key]) ~ "\n";
  }
  s
});

let blup = new TestB(123);

puts(blup.a , " ", blup.x, " " , (blup instanceof Test) ? "true" : "false");
blup.b();

puts(Test.className);
puts(bla.className);
puts(TestB.className);
puts(blup.className);

var piep = new blup.classType(42);

puts(piep.a);

readLine();
----

=== Modules/Namespaces

[source,javascript]
----
module TestModule {

  class TestClass {

    var a = 0;

    constructor(reg v){
      this.a = v;
    }

    function b(){
      puts(this.a);
    }

  }

  function TestClass::c(){
    puts(this.a * 2);
  }

}

module OtherTestModule {

  class TestClass {

    class TestClassInsideTestClass {

      module TestModuleInsideTestClassInsideTestClass {
      }

    }

    var a = 0;

    constructor(var v){
      this.a = v + v;
    }

    function b(){
      puts(this.a);
    }

  }

  function TestClass.c(){
    puts(this.a * 2);
  }

}

var TestClassInstanceFromTestModule = new TestModule.TestClass(2);
TestClassInstanceFromTestModule.b();
TestClassInstanceFromTestModule.c();

puts();

var TestClassInstanceFromOtherTestModule = new OtherTestModule.TestClass(2);
TestClassInstanceFromOtherTestModule.b();
TestClassInstanceFromOtherTestModule.c();
----

=== Hash events/Operator overloading

[source,javascript]
----
var Vector = {
  create: function(reg vx=0, reg vy=0, reg vz=0){
    return setHashEvents({
                           prototype: this,
                           x: vx,
                           y: vy,
                           z: vz
                         }, this);
  },
  __add: fastfunction(reg a, reg b){
    // Important hint: "this" can be null here (even in non-fastfunction functions), so doesn't use it here! :-)
    if((a instanceof Vector) && (b instanceof Vector)){
      return new Vector(a.x + b.x, a.y + b.y, a.z + b.z);
    }else{
      throw "No vector?";
    }
  },
  __sub: fastfunction(reg a, reg b){
    // Important hint: "this" can be null here (even in non-fastfunction functions), so doesn't use it here! :-)
    if((a instanceof Vector) && (b instanceof Vector)){
      return new Vector(a.x - b.x, a.y - b.y, a.z - b.z);
    }else{
      throw "No vector?";
    }
  },
  __mul:fastfunction(reg a, reg b){
    // Important hint: "this" can be null here (even in non-fastfunction functions), so doesn't use it here! :-)
    if((a instanceof Vector) && (b instanceof Vector)){
      return new Vector(a.x * b.x, a.y * b.y, a.z * b.z);
    }else{
      throw "No vector?";
    }
  },
  __div: fastfunction(reg a, reg b){
    // Important hint: "this" can be null here (even in non-fastfunction functions), so doesn't use it here! :-)
    if((a instanceof Vector) && (b instanceof Vector)){
      return new Vector(a.x / b.x, a.y / b.y, a.z / b.z);
    }else{
      throw "No vector?";
    }
  }
};

var va = new Vector(1, 2, 3);
var vb = new Vector(10, 20, 30);

var vc = va + vb;
puts(vc.x, " ", vc.y, " ", vc.z);

vc -= vb;
puts(vc.x, " ", vc.y, " ", vc.z);

vc *= vb;
puts(vc.x, " ", vc.y, " ", vc.z);

vc /= (va*vb);
puts(vc.x, " ", vc.y, " ", vc.z);

readLine();
----

=== Regular expressions

[source,javascript]
----
var expr = "", lineRegExp = /^(.*)\\s*$/, match = [], i = 0, currentScope = {};
while(1){
  print((expr === "") ? "> " : "\\ ");
  if(match = lineRegExp.match(line = readLine()))  {
    expr ~= match[0][1] ~ "\n";
    continue;
  }
  if((expr ~= line) === ""){
    break;
  }
  try{
    print("< " ~ eval(expr, "<eval>", [], null, currentScope) ~ "\n");
  }catch(err){
    for(i = err.size() - 1; i >= 0; i--){
      print(err[i] ~ " ");
    }
    print("\n");
  }
  expr = "";
}
----

=== Exception handling

[source,javascript]
----
try{
  print("Hello ");
}catch(c){
  print("dear ");
}finally{
  print("World!\n");
}

try{
  print("Hello ");
  throw 123;
}catch(c){
  print("dear ");
}finally{
  print("World!\n");
}
----

=== When

[source,javascript]
----
let aValue = 5;
when(aValue){
  case(5 .. 10, 15 .. 17){
    puts("Hey! ", aValue);
    aValue++;
    retry;
  }
  case(18){
    puts("Hi! ", aValue);
    fallthrough;
  }
  case(19){
    puts("Hallo!");
  }
  else{
    puts("Ups!");
  }
}
----

=== Switch

[source,javascript]
----
let aValue = 5;
switch(aValue){
  case 1:
  case 5:
  case 7:
  case 10:
    puts("Hey! ", aValue);
    break;
  case 18:
    puts("Hi! ", aValue);
  case 19:
    puts("Hallo!");
    break;
  default:
    puts("Ups!");
    break;
}
----

=== And more!

And much more!
